services:
  reverse-proxy:
    image: caddy
    command: "caddy reverse-proxy --from :80 --to jenkins:8080"
    container_name: caddy
    ports:
      - 80:80
    depends_on:
      - jenkins
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock